-- ClimaLens Supabase Initial Schema

-- 0. Wipe old fake tables
DROP TABLE IF EXISTS public.destinations;
DROP TABLE IF EXISTS public.hazard_reports;

-- 1. Create the Destinations Table
CREATE TABLE IF NOT EXISTS public.destinations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    district TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    risk_tier TEXT DEFAULT 'risk.low',
    risk_color TEXT DEFAULT '#22C55E',
    suitability_score INTEGER DEFAULT 0,
    safety_score INTEGER DEFAULT 0,
    comfort_score INTEGER DEFAULT 0,
    risk_score INTEGER DEFAULT 0,
    forecast_confidence INTEGER DEFAULT 0,
    community_activity INTEGER DEFAULT 0,
    tags TEXT[] DEFAULT '{}',
    weather TEXT DEFAULT 'Unknown',
    temp TEXT DEFAULT '--°C',
    optimal_months INT4[],
    activities TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE destinations ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access on destinations" 
ON destinations FOR SELECT 
TO anon
USING (true);

-- Step 4: Insert Real Base Locations (Scores will be updated by FastAPI/AI)
INSERT INTO public.destinations (id, name, district, latitude, longitude, tags)
VALUES
    ('galle_face_green', 'Galle Face Green', 'Colombo', 6.9271, 79.8456, '{"interests.culture"}'),
  ('mount_lavinia_beach', 'Mount Lavinia Beach', 'Colombo', 6.8396, 79.8636, '{"interests.surfing","interests.beaches"}'),
  ('viharamahadevi_park', 'Viharamahadevi Park', 'Colombo', 6.9126, 79.8612, '{"interests.wildlife","interests.hiking"}'),
  ('national_museum', 'National Museum', 'Colombo', 6.9105, 79.8617, '{"interests.culture"}'),
  ('gangaramaya_temple', 'Gangaramaya Temple', 'Colombo', 6.9161, 79.8569, '{"interests.culture"}'),
  ('kelaniya_temple', 'Kelaniya Temple', 'Colombo', 6.9532, 79.9192, '{"interests.culture"}'),
  ('independence_square', 'Independence Square', 'Colombo', 6.9042, 79.8675, '{"interests.culture"}'),
  ('beira_lake', 'Beira Lake', 'Colombo', 6.927, 79.855, '{"interests.culture"}'),
  ('jami_ul_alfar_mosque', 'Jami Ul-Alfar Mosque', 'Colombo', 6.9381, 79.8511, '{"interests.culture"}'),
  ('nelum_pokuna', 'Nelum Pokuna', 'Colombo', 6.9111, 79.8633, '{"interests.culture"}'),
  ('negombo_beach', 'Negombo Beach', 'Gampaha', 7.2111, 79.8386, '{"interests.surfing","interests.beaches"}'),
  ('guruge_nature_park', 'Guruge Nature Park', 'Gampaha', 7.0863, 79.8943, '{"interests.wildlife","interests.hiking"}'),
  ('muthurajawela_marsh', 'Muthurajawela Marsh', 'Gampaha', 7.0833, 79.8667, '{"interests.culture"}'),
  ('attanagalla_temple', 'Attanagalla Temple', 'Gampaha', 7.1264, 80.1171, '{"interests.culture"}'),
  ('henarathgoda_botanical_garden', 'Henarathgoda Botanical Garden', 'Gampaha', 7.1009, 79.9928, '{"interests.culture"}'),
  ('negombo_dutch_fort', 'Negombo Dutch Fort', 'Gampaha', 7.2078, 79.8291, '{"interests.culture"}'),
  ('st._marys_church_negombo', 'St. Marys Church Negombo', 'Gampaha', 7.2103, 79.8335, '{"interests.culture"}'),
  ('browns_beach', 'Browns Beach', 'Gampaha', 7.2341, 79.8402, '{"interests.surfing","interests.beaches"}'),
  ('angurukaramulla_temple', 'Angurukaramulla Temple', 'Gampaha', 7.2117, 79.8466, '{"interests.culture"}'),
  ('kelaniya_raja_maha_vihara', 'Kelaniya Raja Maha Vihara', 'Gampaha', 6.9532, 79.9192, '{"interests.culture"}'),
  ('richmond_castle', 'Richmond Castle', 'Kalutara', 6.5898, 79.9608, '{"interests.culture"}'),
  ('brief_garden', 'Brief Garden', 'Kalutara', 6.4385, 80.0075, '{"interests.culture"}'),
  ('kalutara_bodhiya', 'Kalutara Bodhiya', 'Kalutara', 6.5862, 79.9592, '{"interests.culture"}'),
  ('pahiyangala_cave', 'Pahiyangala Cave', 'Kalutara', 6.6433, 80.1983, '{"interests.culture"}'),
  ('panadura_beach', 'Panadura Beach', 'Kalutara', 6.7088, 79.9011, '{"interests.surfing","interests.beaches"}'),
  ('calido_beach', 'Calido Beach', 'Kalutara', 6.5869, 79.9545, '{"interests.surfing","interests.beaches"}'),
  ('kande_viharaya', 'Kande Viharaya', 'Kalutara', 6.4468, 80.0003, '{"interests.culture"}'),
  ('beruwala_lighthouse', 'Beruwala Lighthouse', 'Kalutara', 6.4716, 79.9823, '{"interests.culture"}'),
  ('moragalla_beach', 'Moragalla Beach', 'Kalutara', 6.4363, 79.9983, '{"interests.surfing","interests.beaches"}'),
  ('thudugala_ella', 'Thudugala Ella', 'Kalutara', 6.5167, 80.0667, '{"interests.culture"}'),
  ('temple_of_the_tooth', 'Temple of the Tooth', 'Kandy', 7.2906, 80.6337, '{"interests.culture"}'),
  ('peradeniya_botanical_gardens', 'Peradeniya Botanical Gardens', 'Kandy', 7.2685, 80.5966, '{"interests.culture"}'),
  ('udawatta_kele_sanctuary', 'Udawatta Kele Sanctuary', 'Kandy', 7.3005, 80.6402, '{"interests.wildlife","interests.hiking"}'),
  ('bahirawakanda_vihara', 'Bahirawakanda Vihara', 'Kandy', 7.2905, 80.6274, '{"interests.culture"}'),
  ('hanathana_mountain_range', 'Hanathana Mountain Range', 'Kandy', 7.2519, 80.6358, '{"interests.hiking"}'),
  ('lankatilaka_vihara', 'Lankatilaka Vihara', 'Kandy', 7.2341, 80.5645, '{"interests.culture"}'),
  ('gadaladeniya_vihara', 'Gadaladeniya Vihara', 'Kandy', 7.2568, 80.5562, '{"interests.culture"}'),
  ('embekka_devalaya', 'Embekka Devalaya', 'Kandy', 7.2173, 80.5654, '{"interests.culture"}'),
  ('kandy_lake', 'Kandy Lake', 'Kandy', 7.2921, 80.6384, '{"interests.culture"}'),
  ('ceylon_tea_museum', 'Ceylon Tea Museum', 'Kandy', 7.2662, 80.6321, '{"interests.culture"}'),
  ('sigiriya_rock_fortress', 'Sigiriya Rock Fortress', 'Matale', 7.957, 80.7603, '{"interests.hiking"}'),
  ('dambulla_cave_temple', 'Dambulla Cave Temple', 'Matale', 7.8566, 80.6485, '{"interests.culture"}'),
  ('pidurangala_rock', 'Pidurangala Rock', 'Matale', 7.9663, 80.7634, '{"interests.hiking"}'),
  ('sembuwatta_lake', 'Sembuwatta Lake', 'Matale', 7.4297, 80.6868, '{"interests.culture"}'),
  ('knuckles_mountain_range', 'Knuckles Mountain Range', 'Matale', 7.4208, 80.7937, '{"interests.hiking"}'),
  ('aluvihare_rock_temple', 'Aluvihare Rock Temple', 'Matale', 7.4988, 80.6214, '{"interests.hiking"}'),
  ('riverston', 'Riverston', 'Matale', 7.5283, 80.7381, '{"interests.culture"}'),
  ('pitawala_pathana', 'Pitawala Pathana', 'Matale', 7.5458, 80.7511, '{"interests.culture"}'),
  ('sera_ella', 'Sera Ella', 'Matale', 7.5755, 80.7417, '{"interests.culture"}'),
  ('bambarakiri_ella', 'Bambarakiri Ella', 'Matale', 7.4913, 80.7061, '{"interests.culture"}'),
  ('horton_plains', 'Horton Plains', 'Nuwara Eliya', 6.8045, 80.8066, '{"interests.culture"}'),
  ('gregory_lake', 'Gregory Lake', 'Nuwara Eliya', 6.9587, 80.7766, '{"interests.culture"}'),
  ('hakgala_botanical_garden', 'Hakgala Botanical Garden', 'Nuwara Eliya', 6.9255, 80.8202, '{"interests.culture"}'),
  ('victoria_park', 'Victoria Park', 'Nuwara Eliya', 6.9712, 80.7681, '{"interests.wildlife","interests.hiking"}'),
  ('st._clairs_falls', 'St. Clairs Falls', 'Nuwara Eliya', 6.9388, 80.6318, '{"interests.hiking"}'),
  ('devon_falls', 'Devon Falls', 'Nuwara Eliya', 6.9429, 80.6121, '{"interests.hiking"}'),
  ('pedro_tea_estate', 'Pedro Tea Estate', 'Nuwara Eliya', 6.9786, 80.7892, '{"interests.culture"}'),
  ('lovers_leap_waterfall', 'Lovers Leap Waterfall', 'Nuwara Eliya', 6.9763, 80.7885, '{"interests.culture"}'),
  ('ambewela_farms', 'Ambewela Farms', 'Nuwara Eliya', 6.8778, 80.8066, '{"interests.culture"}'),
  ('single_tree_hill', 'Single Tree Hill', 'Nuwara Eliya', 6.9566, 80.7621, '{"interests.culture"}'),
  ('galle_fort', 'Galle Fort', 'Galle', 6.0328, 80.2149, '{"interests.culture"}'),
  ('unawatuna_beach', 'Unawatuna Beach', 'Galle', 6.0125, 80.2483, '{"interests.surfing","interests.beaches"}'),
  ('hikkaduwa_coral_reef', 'Hikkaduwa Coral Reef', 'Galle', 6.1363, 80.0991, '{"interests.surfing","interests.beaches"}'),
  ('koggala_lake', 'Koggala Lake', 'Galle', 5.9922, 80.3236, '{"interests.culture"}'),
  ('rumassala_pagoda', 'Rumassala Pagoda', 'Galle', 6.0163, 80.2403, '{"interests.culture"}'),
  ('jungle_beach', 'Jungle Beach', 'Galle', 6.0175, 80.2383, '{"interests.surfing","interests.beaches"}'),
  ('martin_wickramasinghe_museum', 'Martin Wickramasinghe Museum', 'Galle', 5.9961, 80.3344, '{"interests.culture"}'),
  ('yatagala_raja_maha_viharaya', 'Yatagala Raja Maha Viharaya', 'Galle', 6.0286, 80.2588, '{"interests.culture"}'),
  ('dalawella_beach', 'Dalawella Beach', 'Galle', 6.0021, 80.2644, '{"interests.surfing","interests.beaches"}'),
  ('mihiripenna_beach', 'Mihiripenna Beach', 'Galle', 5.9995, 80.2781, '{"interests.surfing","interests.beaches"}'),
  ('mirissa_beach', 'Mirissa Beach', 'Matara', 5.9483, 80.4716, '{"interests.surfing","interests.beaches"}'),
  ('polhena_beach', 'Polhena Beach', 'Matara', 5.9353, 80.5218, '{"interests.surfing","interests.beaches"}'),
  ('dondra_head_lighthouse', 'Dondra Head Lighthouse', 'Matara', 5.9219, 80.5898, '{"interests.culture"}'),
  ('weligama_bay', 'Weligama Bay', 'Matara', 5.9723, 80.4283, '{"interests.surfing","interests.beaches"}'),
  ('star_fort', 'Star Fort', 'Matara', 5.9463, 80.5484, '{"interests.culture"}'),
  ('coconut_tree_hill', 'Coconut Tree Hill', 'Matara', 5.9416, 80.4633, '{"interests.culture"}'),
  ('secret_beach_mirissa', 'Secret Beach Mirissa', 'Matara', 5.9444, 80.4552, '{"interests.surfing","interests.beaches"}'),
  ('weherahena_temple', 'Weherahena Temple', 'Matara', 5.9555, 80.5677, '{"interests.culture"}'),
  ('parrot_rock_bridge', 'Parrot Rock Bridge', 'Matara', 5.9458, 80.4627, '{"interests.hiking"}'),
  ('matara_paravi_duwa_temple', 'Matara Paravi Duwa Temple', 'Matara', 5.9416, 80.5458, '{"interests.culture"}'),
  ('yala_national_park', 'Yala National Park', 'Hambantota', 6.3683, 81.5161, '{"interests.wildlife","interests.hiking"}'),
  ('bundala_national_park', 'Bundala National Park', 'Hambantota', 6.1833, 81.2333, '{"interests.wildlife","interests.hiking"}'),
  ('ridiyagama_safari_park', 'Ridiyagama Safari Park', 'Hambantota', 6.2238, 80.9933, '{"interests.wildlife","interests.hiking"}'),
  ('kumana_border', 'Kumana Border', 'Hambantota', 6.5614, 81.7335, '{"interests.culture"}'),
  ('kataragama_temple', 'Kataragama Temple', 'Hambantota', 6.4132, 81.3323, '{"interests.culture"}'),
  ('hambantota_salt_pans', 'Hambantota Salt Pans', 'Hambantota', 6.1264, 81.1278, '{"interests.culture"}'),
  ('dry_zone_botanic_gardens', 'Dry Zone Botanic Gardens', 'Hambantota', 6.1558, 80.9858, '{"interests.culture"}'),
  ('mirijjawila', 'Mirijjawila', 'Hambantota', 6.1667, 81.0833, '{"interests.culture"}'),
  ('ussangoda_national_park', 'Ussangoda National Park', 'Hambantota', 6.1158, 80.9881, '{"interests.wildlife","interests.hiking"}'),
  ('kalametiya_bird_sanctuary', 'Kalametiya Bird Sanctuary', 'Hambantota', 6.1033, 80.9416, '{"interests.wildlife","interests.hiking"}'),
  ('jaffna_fort', 'Jaffna Fort', 'Jaffna', 9.6615, 80.0074, '{"interests.culture"}'),
  ('nallur_kandaswamy_temple', 'Nallur Kandaswamy Temple', 'Jaffna', 9.6748, 80.0298, '{"interests.culture"}'),
  ('casuarina_beach', 'Casuarina Beach', 'Jaffna', 9.7611, 79.8824, '{"interests.surfing","interests.beaches"}'),
  ('delft_island', 'Delft Island', 'Jaffna', 9.5085, 79.6791, '{"interests.culture"}'),
  ('keerimalai_springs', 'Keerimalai Springs', 'Jaffna', 9.8166, 80.0135, '{"interests.culture"}'),
  ('nainativu_nagapooshani', 'Nainativu Nagapooshani', 'Jaffna', 9.6166, 79.7719, '{"interests.culture"}'),
  ('jaffna_public_library', 'Jaffna Public Library', 'Jaffna', 9.6622, 80.0125, '{"interests.culture"}'),
  ('dambakola_patuna', 'Dambakola Patuna', 'Jaffna', 9.7891, 79.9405, '{"interests.culture"}'),
  ('point_pedro', 'Point Pedro', 'Jaffna', 9.8244, 80.2333, '{"interests.culture"}'),
  ('kantharodai_ruins', 'Kantharodai Ruins', 'Jaffna', 9.7431, 79.9888, '{"interests.culture"}'),
  ('iranamadu_tank', 'Iranamadu Tank', 'Kilinochchi', 9.3245, 80.4079, '{"interests.culture"}'),
  ('kilinochchi_war_memorial', 'Kilinochchi War Memorial', 'Kilinochchi', 9.3888, 80.4005, '{"interests.culture"}'),
  ('pooneryn_fort', 'Pooneryn Fort', 'Kilinochchi', 9.5028, 80.1983, '{"interests.culture"}'),
  ('gautamavaram', 'Gautamavaram', 'Kilinochchi', 9.3333, 80.4167, '{"interests.culture"}'),
  ('vaddakachchi', 'Vaddakachchi', 'Kilinochchi', 9.3512, 80.4571, '{"interests.culture"}'),
  ('akkarayan_kulam', 'Akkarayan Kulam', 'Kilinochchi', 9.2133, 80.3208, '{"interests.culture"}'),
  ('murikandy_pillayar_shrine', 'Murikandy Pillayar Shrine', 'Kilinochchi', 9.2558, 80.3802, '{"interests.culture"}'),
  ('elephant_pass', 'Elephant Pass', 'Kilinochchi', 9.5258, 80.4036, '{"interests.culture"}'),
  ('kilinochchi_water_tower', 'Kilinochchi Water Tower', 'Kilinochchi', 9.3908, 80.3955, '{"interests.culture"}'),
  ('sivan_kovil_kilinochchi', 'Sivan Kovil Kilinochchi', 'Kilinochchi', 9.3955, 80.3999, '{"interests.culture"}'),
  ('mannar_fort', 'Mannar Fort', 'Mannar', 8.9774, 79.907, '{"interests.culture"}'),
  ('talaimannar_pier', 'Talaimannar Pier', 'Mannar', 9.0964, 79.7216, '{"interests.culture"}'),
  ('thiruketheeswaram_kovil', 'Thiruketheeswaram Kovil', 'Mannar', 9.0069, 79.9575, '{"interests.culture"}'),
  ('adams_bridge', 'Adams Bridge', 'Mannar', 9.0667, 79.5833, '{"interests.culture"}'),
  ('doric_at_arippu', 'Doric at Arippu', 'Mannar', 8.7772, 79.9205, '{"interests.culture"}'),
  ('giants_tank', 'Giants Tank', 'Mannar', 8.8683, 80.0408, '{"interests.culture"}'),
  ('shrine_of_our_lady_of_madhu', 'Shrine of Our Lady of Madhu', 'Mannar', 8.8552, 80.2033, '{"interests.culture"}'),
  ('mannar_bird_sanctuary', 'Mannar Bird Sanctuary', 'Mannar', 9.0222, 79.8822, '{"interests.wildlife","interests.hiking"}'),
  ('keeri_beach', 'Keeri Beach', 'Mannar', 8.9833, 79.8666, '{"interests.surfing","interests.beaches"}'),
  ('baobab_tree_mannar', 'Baobab Tree Mannar', 'Mannar', 8.9866, 79.9144, '{"interests.culture"}'),
  ('vavuniya_grand_jummah_mosque', 'Vavuniya Grand Jummah Mosque', 'Vavuniya', 8.7516, 80.4971, '{"interests.culture"}'),
  ('kandasamy_kovil', 'Kandasamy Kovil', 'Vavuniya', 8.7533, 80.4981, '{"interests.culture"}'),
  ('madukanda_vihara', 'Madukanda Vihara', 'Vavuniya', 8.7303, 80.5369, '{"interests.culture"}'),
  ('irakperiyakulam', 'Irakperiyakulam', 'Vavuniya', 8.7025, 80.4855, '{"interests.culture"}'),
  ('pampaimadu', 'Pampaimadu', 'Vavuniya', 8.7758, 80.4819, '{"interests.culture"}'),
  ('vavuniya_archaeological_museum', 'Vavuniya Archaeological Museum', 'Vavuniya', 8.7555, 80.4999, '{"interests.culture"}'),
  ('kalukundamaha_vihara', 'Kalukundamaha Vihara', 'Vavuniya', 8.7111, 80.4722, '{"interests.culture"}'),
  ('thandikulam', 'Thandikulam', 'Vavuniya', 8.7733, 80.5055, '{"interests.culture"}'),
  ('vavuniya_lake', 'Vavuniya Lake', 'Vavuniya', 8.7499, 80.4933, '{"interests.culture"}'),
  ('omanthai', 'Omanthai', 'Vavuniya', 8.8655, 80.5188, '{"interests.culture"}'),
  ('mullaitivu_beach', 'Mullaitivu Beach', 'Mullaitivu', 9.2667, 80.8167, '{"interests.surfing","interests.beaches"}'),
  ('nanthikadal_lagoon', 'Nanthikadal Lagoon', 'Mullaitivu', 9.3083, 80.7611, '{"interests.surfing","interests.beaches"}'),
  ('vattappalai_kannaki_amman', 'Vattappalai Kannaki Amman', 'Mullaitivu', 9.2561, 80.7716, '{"interests.culture"}'),
  ('nayaru_beach', 'Nayaru Beach', 'Mullaitivu', 9.1305, 80.8411, '{"interests.surfing","interests.beaches"}'),
  ('kokkilai_bird_sanctuary', 'Kokkilai Bird Sanctuary', 'Mullaitivu', 9.0083, 80.9583, '{"interests.wildlife","interests.hiking"}'),
  ('vadduvakal_bridge', 'Vadduvakal Bridge', 'Mullaitivu', 9.2888, 80.7966, '{"interests.culture"}'),
  ('chundikulam_bird_sanctuary', 'Chundikulam Bird Sanctuary', 'Mullaitivu', 9.5166, 80.4666, '{"interests.wildlife","interests.hiking"}'),
  ('muthiyankaddu_kulam', 'Muthiyankaddu Kulam', 'Mullaitivu', 9.1666, 80.6833, '{"interests.culture"}'),
  ('puthukkudiyiruppu_war_museum', 'Puthukkudiyiruppu War Museum', 'Mullaitivu', 9.3166, 80.7333, '{"interests.culture"}'),
  ('oddusuddan', 'Oddusuddan', 'Mullaitivu', 9.1555, 80.6544, '{"interests.culture"}'),
  ('pasikudah_beach', 'Pasikudah Beach', 'Batticaloa', 7.9221, 81.5606, '{"interests.surfing","interests.beaches"}'),
  ('kallady_bridge', 'Kallady Bridge', 'Batticaloa', 7.7121, 81.7061, '{"interests.culture"}'),
  ('batticaloa_fort', 'Batticaloa Fort', 'Batticaloa', 7.7153, 81.6963, '{"interests.culture"}'),
  ('kalkudah_beach', 'Kalkudah Beach', 'Batticaloa', 7.9333, 81.5583, '{"interests.surfing","interests.beaches"}'),
  ('batticaloa_lighthouse', 'Batticaloa Lighthouse', 'Batticaloa', 7.7558, 81.6789, '{"interests.culture"}'),
  ('unnichchai_tank', 'Unnichchai Tank', 'Batticaloa', 7.6469, 81.4727, '{"interests.culture"}'),
  ('batticaloa_lagoon', 'Batticaloa Lagoon', 'Batticaloa', 7.7166, 81.6833, '{"interests.surfing","interests.beaches"}'),
  ('navalady_beach', 'Navalady Beach', 'Batticaloa', 7.7288, 81.7166, '{"interests.surfing","interests.beaches"}'),
  ('kokkadichcholai_temple', 'Kokkadichcholai Temple', 'Batticaloa', 7.6166, 81.6833, '{"interests.culture"}'),
  ('mamangam_temple', 'Mamangam Temple', 'Batticaloa', 7.7411, 81.6722, '{"interests.culture"}'),
  ('arugam_bay', 'Arugam Bay', 'Ampara', 6.8407, 81.8217, '{"interests.surfing","interests.beaches"}'),
  ('muhudu_maha_viharaya', 'Muhudu Maha Viharaya', 'Ampara', 6.8778, 81.8291, '{"interests.culture"}'),
  ('deegawapiya', 'Deegawapiya', 'Ampara', 7.2341, 81.6702, '{"interests.culture"}'),
  ('magul_maha_viharaya', 'Magul Maha Viharaya', 'Ampara', 6.8744, 81.6144, '{"interests.culture"}'),
  ('gal_oya_national_park', 'Gal Oya National Park', 'Ampara', 7.2144, 81.3653, '{"interests.wildlife","interests.hiking"}'),
  ('pottuvil_point', 'Pottuvil Point', 'Ampara', 6.8731, 81.8344, '{"interests.culture"}'),
  ('panama_beach', 'Panama Beach', 'Ampara', 6.7666, 81.8, '{"interests.surfing","interests.beaches"}'),
  ('lahugala_kitulana', 'Lahugala Kitulana', 'Ampara', 6.8525, 81.7058, '{"interests.culture"}'),
  ('senanayake_samudraya', 'Senanayake Samudraya', 'Ampara', 7.2166, 81.5333, '{"interests.culture"}'),
  ('ampara_tank', 'Ampara Tank', 'Ampara', 7.2833, 81.6833, '{"interests.culture"}'),
  ('pigeon_island', 'Pigeon Island', 'Trincomalee', 8.7236, 81.2001, '{"interests.culture"}'),
  ('koneswaram_temple', 'Koneswaram Temple', 'Trincomalee', 8.5835, 81.2329, '{"interests.culture"}'),
  ('nilaveli_beach', 'Nilaveli Beach', 'Trincomalee', 8.6833, 81.1833, '{"interests.surfing","interests.beaches"}'),
  ('marble_beach', 'Marble Beach', 'Trincomalee', 8.5361, 81.1994, '{"interests.surfing","interests.beaches"}'),
  ('fort_frederick', 'Fort Frederick', 'Trincomalee', 8.5822, 81.2319, '{"interests.culture"}'),
  ('uppuveli_beach', 'Uppuveli Beach', 'Trincomalee', 8.6083, 81.2183, '{"interests.surfing","interests.beaches"}'),
  ('kanniya_hot_springs', 'Kanniya Hot Springs', 'Trincomalee', 8.6072, 81.1952, '{"interests.culture"}'),
  ('trincomalee_war_cemetery', 'Trincomalee War Cemetery', 'Trincomalee', 8.6088, 81.2177, '{"interests.culture"}'),
  ('velgam_vehera', 'Velgam Vehera', 'Trincomalee', 8.6666, 81.1666, '{"interests.culture"}'),
  ('swami_rock', 'Swami Rock', 'Trincomalee', 8.5822, 81.2333, '{"interests.hiking"}'),
  ('ethagala_elephant_rock', 'Ethagala Elephant Rock', 'Kurunegala', 7.4883, 80.3664, '{"interests.hiking"}'),
  ('ridi_viharaya', 'Ridi Viharaya', 'Kurunegala', 7.5759, 80.4281, '{"interests.culture"}'),
  ('kurunegala_lake', 'Kurunegala Lake', 'Kurunegala', 7.4853, 80.3683, '{"interests.culture"}'),
  ('yapahuwa', 'Yapahuwa', 'Kurunegala', 7.7853, 80.3013, '{"interests.culture"}'),
  ('athugala_viharaya', 'Athugala Viharaya', 'Kurunegala', 7.4872, 80.3655, '{"interests.culture"}'),
  ('panduwasnuwara', 'Panduwasnuwara', 'Kurunegala', 7.6083, 80.0888, '{"interests.culture"}'),
  ('arankele_forest_monastery', 'Arankele Forest Monastery', 'Kurunegala', 7.6416, 80.4208, '{"interests.wildlife","interests.hiking"}'),
  ('kurunegala_clock_tower', 'Kurunegala Clock Tower', 'Kurunegala', 7.4866, 80.3644, '{"interests.culture"}'),
  ('padeniya_raja_maha_vihara', 'Padeniya Raja Maha Vihara', 'Kurunegala', 7.6533, 80.2088, '{"interests.culture"}'),
  ('dambadeniya', 'Dambadeniya', 'Kurunegala', 7.3666, 80.15, '{"interests.culture"}'),
  ('kalpitiya_peninsula', 'Kalpitiya Peninsula', 'Puttalam', 8.2329, 79.7745, '{"interests.surfing","interests.beaches"}'),
  ('wilpattu_national_park', 'Wilpattu National Park', 'Puttalam', 8.4411, 80.0051, '{"interests.wildlife","interests.hiking"}'),
  ('munneswaram_temple', 'Munneswaram Temple', 'Puttalam', 7.5833, 79.8333, '{"interests.culture"}'),
  ('st_annes_shrine_talawila', 'St Annes Shrine Talawila', 'Puttalam', 8.0864, 79.7214, '{"interests.culture"}'),
  ('anawilundawa_bird_sanctuary', 'Anawilundawa Bird Sanctuary', 'Puttalam', 7.7125, 79.8242, '{"interests.wildlife","interests.hiking"}'),
  ('puttalam_lagoon', 'Puttalam Lagoon', 'Puttalam', 8.0833, 79.8, '{"interests.surfing","interests.beaches"}'),
  ('alankuda_beach', 'Alankuda Beach', 'Puttalam', 8.0333, 79.7166, '{"interests.surfing","interests.beaches"}'),
  ('dutch_fort_kalpitiya', 'Dutch Fort Kalpitiya', 'Puttalam', 8.2305, 79.7611, '{"interests.culture"}'),
  ('baththalangunduwa', 'Baththalangunduwa', 'Puttalam', 8.5208, 79.7638, '{"interests.culture"}'),
  ('chilaw_sand_spit', 'Chilaw Sand Spit', 'Puttalam', 7.5866, 79.7899, '{"interests.culture"}'),
  ('ruwanwelisaya', 'Ruwanwelisaya', 'Anuradhapura', 8.35, 80.3965, '{"interests.culture"}'),
  ('mihintale', 'Mihintale', 'Anuradhapura', 8.3512, 80.5173, '{"interests.culture"}'),
  ('sri_maha_bodhi', 'Sri Maha Bodhi', 'Anuradhapura', 8.3444, 80.3972, '{"interests.culture"}'),
  ('jetavanaramaya', 'Jetavanaramaya', 'Anuradhapura', 8.3526, 80.4027, '{"interests.culture"}'),
  ('abhayagiri', 'Abhayagiri', 'Anuradhapura', 8.3619, 80.3963, '{"interests.culture"}'),
  ('isurumuniya', 'Isurumuniya', 'Anuradhapura', 8.3347, 80.3908, '{"interests.culture"}'),
  ('thuparamaya', 'Thuparamaya', 'Anuradhapura', 8.3561, 80.3963, '{"interests.culture"}'),
  ('kuttam_pokuna', 'Kuttam Pokuna', 'Anuradhapura', 8.3666, 80.4011, '{"interests.culture"}'),
  ('samadhi_statue', 'Samadhi Statue', 'Anuradhapura', 8.3622, 80.3988, '{"interests.culture"}'),
  ('nuwara_wewa', 'Nuwara Wewa', 'Anuradhapura', 8.3416, 80.4288, '{"interests.culture"}'),
  ('vatadage', 'Vatadage', 'Polonnaruwa', 7.9463, 81.0006, '{"interests.culture"}'),
  ('parakrama_samudra', 'Parakrama Samudra', 'Polonnaruwa', 7.9254, 80.9859, '{"interests.culture"}'),
  ('gal_vihara', 'Gal Vihara', 'Polonnaruwa', 7.9547, 81.0055, '{"interests.culture"}'),
  ('rankoth_vehera', 'Rankoth Vehera', 'Polonnaruwa', 7.9519, 81.0024, '{"interests.culture"}'),
  ('lankatilaka', 'Lankatilaka', 'Polonnaruwa', 7.9527, 81.0044, '{"interests.culture"}'),
  ('somawathiya', 'Somawathiya', 'Polonnaruwa', 8.1158, 81.1611, '{"interests.culture"}'),
  ('nissanka_latha_mandapaya', 'Nissanka Latha Mandapaya', 'Polonnaruwa', 7.9472, 81.0, '{"interests.culture"}'),
  ('lotus_pond', 'Lotus Pond', 'Polonnaruwa', 7.9622, 81.0055, '{"interests.culture"}'),
  ('polonnaruwa_museum', 'Polonnaruwa Museum', 'Polonnaruwa', 7.9333, 80.9999, '{"interests.culture"}'),
  ('thivanka_image_house', 'Thivanka Image House', 'Polonnaruwa', 7.9666, 81.0055, '{"interests.culture"}'),
  ('nine_arches_bridge', 'Nine Arches Bridge', 'Badulla', 6.8767, 81.0608, '{"interests.culture"}'),
  ('dunhinda_falls', 'Dunhinda Falls', 'Badulla', 7.0163, 81.0617, '{"interests.hiking"}'),
  ('little_adams_peak', 'Little Adams Peak', 'Badulla', 6.8661, 81.0583, '{"interests.hiking"}'),
  ('muthiyangana', 'Muthiyangana', 'Badulla', 6.9886, 81.0561, '{"interests.culture"}'),
  ('diyaluma_falls', 'Diyaluma Falls', 'Badulla', 6.7264, 80.9994, '{"interests.hiking"}'),
  ('bogoda_wooden_bridge', 'Bogoda Wooden Bridge', 'Badulla', 6.9372, 81.0, '{"interests.culture"}'),
  ('ravana_falls', 'Ravana Falls', 'Badulla', 6.8408, 81.0547, '{"interests.hiking"}'),
  ('liptons_seat', 'Liptons Seat', 'Badulla', 6.7802, 81.0183, '{"interests.culture"}'),
  ('ella_rock', 'Ella Rock', 'Badulla', 6.8533, 81.0458, '{"interests.hiking"}'),
  ('bambarakanda_falls', 'Bambarakanda Falls', 'Badulla', 6.7733, 80.8288, '{"interests.hiking"}'),
  ('maligawila', 'Maligawila', 'Moneragala', 6.7262, 81.3323, '{"interests.culture"}'),
  ('buduruwagala', 'Buduruwagala', 'Moneragala', 6.6433, 81.0772, '{"interests.culture"}'),
  ('yudaganawa', 'Yudaganawa', 'Moneragala', 6.7833, 81.25, '{"interests.culture"}'),
  ('sella_kataragama', 'Sella Kataragama', 'Moneragala', 6.4366, 81.3211, '{"interests.culture"}'),
  ('moneragala_viharaya', 'Moneragala Viharaya', 'Moneragala', 6.8711, 81.3488, '{"interests.culture"}'),
  ('nilgala_forest_reserve', 'Nilgala Forest Reserve', 'Moneragala', 7.15, 81.3666, '{"interests.wildlife","interests.hiking"}'),
  ('dematamal_viharaya', 'Dematamal Viharaya', 'Moneragala', 6.8088, 81.2722, '{"interests.culture"}'),
  ('kataragama_temple_south', 'Kataragama Temple South', 'Moneragala', 6.4132, 81.3323, '{"interests.culture"}'),
  ('maduru_oya_boundary', 'Maduru Oya Boundary', 'Moneragala', 7.5666, 81.1666, '{"interests.culture"}'),
  ('weheragala_dam', 'Weheragala Dam', 'Moneragala', 6.55, 81.25, '{"interests.culture"}'),
  ('sinharaja', 'Sinharaja', 'Ratnapura', 6.4172, 80.4239, '{"interests.culture"}'),
  ('adams_peak', 'Adams Peak', 'Ratnapura', 6.8096, 80.4994, '{"interests.hiking"}'),
  ('bopath_ella', 'Bopath Ella', 'Ratnapura', 6.8028, 80.3155, '{"interests.culture"}'),
  ('maha_saman_devalaya', 'Maha Saman Devalaya', 'Ratnapura', 6.6853, 80.3725, '{"interests.culture"}'),
  ('udawalawe_national_park', 'Udawalawe National Park', 'Ratnapura', 6.4719, 80.8936, '{"interests.wildlife","interests.hiking"}'),
  ('gem_museum_ratnapura', 'Gem Museum Ratnapura', 'Ratnapura', 6.68, 80.3999, '{"interests.culture"}'),
  ('maduwanwela_walawwa', 'Maduwanwela Walawwa', 'Ratnapura', 6.3072, 80.6402, '{"interests.culture"}'),
  ('warnagala', 'Warnagala', 'Ratnapura', 6.8166, 80.4666, '{"interests.culture"}'),
  ('kithulgala_water_rafting', 'Kithulgala Water Rafting', 'Ratnapura', 6.9958, 80.4133, '{"interests.culture"}'),
  ('makandawa_forest_reserve', 'Makandawa Forest Reserve', 'Ratnapura', 6.9833, 80.4166, '{"interests.wildlife","interests.hiking"}'),
  ('pinnawala', 'Pinnawala', 'Kegalle', 7.3013, 80.3871, '{"interests.culture"}'),
  ('elephant_freedom_project', 'Elephant Freedom Project', 'Kegalle', 7.3013, 80.3888, '{"interests.culture"}'),
  ('ambuluwawa', 'Ambuluwawa', 'Kegalle', 7.1519, 80.5483, '{"interests.culture"}'),
  ('saradiyel_village', 'Saradiyel Village', 'Kegalle', 7.2344, 80.4433, '{"interests.culture"}'),
  ('saligala', 'Saligala', 'Kegalle', 7.1855, 80.2644, '{"interests.culture"}'),
  ('dedigama_kota_vehera', 'Dedigama Kota Vehera', 'Kegalle', 7.2305, 80.2688, '{"interests.culture"}'),
  ('asupini_ella', 'Asupini Ella', 'Kegalle', 7.1266, 80.4666, '{"interests.culture"}'),
  ('algama_falls', 'Algama Falls', 'Kegalle', 7.1666, 80.2333, '{"interests.hiking"}'),
  ('ipolagama_viharaya', 'Ipolagama Viharaya', 'Kegalle', 7.3222, 80.3588, '{"interests.culture"}'),
  ('beligammana', 'Beligammana', 'Kegalle', 7.2588, 80.4133, '{"interests.culture"}')
ON CONFLICT (id) DO NOTHING;

-- 5. Create Historical Disasters Table
CREATE TABLE IF NOT EXISTS public.historical_disasters (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  destination_id text REFERENCES destinations(id) ON DELETE CASCADE,
  year integer,
  type text,
  severity text,
  description text
);

-- Disable Row Level Security (RLS) for historical_disasters to allow public read/write for prototyping
ALTER TABLE public.historical_disasters DISABLE ROW LEVEL SECURITY;

-- 6. Create Itineraries Table (Multi-Destination Trip Planning)
CREATE TABLE IF NOT EXISTS public.itineraries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID,  -- nullable for anonymous/prototype usage
  title TEXT NOT NULL DEFAULT 'My Sri Lanka Trip',
  start_date DATE,
  end_date DATE,
  total_risk_score DOUBLE PRECISION DEFAULT 0,
  total_travel_minutes INTEGER DEFAULT 0,
  status TEXT DEFAULT 'draft',  -- draft, planned, completed
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Create Itinerary Stops Table (ordered destinations within an itinerary)
CREATE TABLE IF NOT EXISTS public.itinerary_stops (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  itinerary_id UUID REFERENCES itineraries(id) ON DELETE CASCADE,
  destination_id TEXT REFERENCES destinations(id) ON DELETE CASCADE,
  stop_order INTEGER NOT NULL DEFAULT 0,
  visit_date DATE,
  travel_minutes_to_next INTEGER DEFAULT 0,  -- estimated travel time to next stop
  predicted_temp DOUBLE PRECISION,
  predicted_precip DOUBLE PRECISION,
  predicted_wind DOUBLE PRECISION,
  predicted_risk TEXT DEFAULT 'Low',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable RLS for prototyping
ALTER TABLE public.itineraries DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.itinerary_stops DISABLE ROW LEVEL SECURITY;
